immortal_process: true
check_episode_files_number_uploaded: false
grabbed_file_identifier_regex: .+-grab.job
downloaded_torrent_file_identifier_regex: .+-finished.job
downloads_team_drive_id: 23lk4kjh5k234thanks
downloads_series_folder_id: 23lk4kjh5k234thanks-
movies_team_drive_id: 23lk4kjh5k234thanks
series_team_drive_id: 23lk4kjh5k234thanks
google_retry_interval: 30
job_files_pick_up_interval: 1

sonarr_api_host: your-sonarr.domain.is
sonarr_api_key: 1y2u2u3u4ui4o5o5hi
sonarr_paths_starter: /tv
radarr_api_host: your-radarr.domain.is
radarr_api_key: 1y2u2u3u4ui4o5o5hi
plex_host: your-plex.domain.is
plex_token: q1Ej435345E2zJj
plex_sections_list_uri: /library/sections
plex_section_refresh_uri: /library/sections/{section_id}/refresh
plex_series_paths_starter: /mnt/mangrana_series